# Generated by Django 4.1.3 on 2023-02-22 18:39

import AlzhimerApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alzhimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to=AlzhimerApp.models.Alzhimer.filepath)),
            ],
        ),
    ]
